version: '3.8'

services:

  db:

    image: postgres:14-alpine3.17
    
    volumes:
      - ./db:/var/lib/postgresql/data

    container_name: properties_db

    ports:
      - 8000:5432

    environment:
      - POSTGRES_PASSWORD=unhackable
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  scraper:
    build: 
      context: ./scraper

    volumes:
      - .:/home/scraper

    container_name: properties_scraper

    ports:
      - 8001:8000

    environment:
      - POSTGRES_HOST=db  # FOR DOCKER COMPOSE NETWORKING
    
    depends_on:
      - db
  
  pgadmin:

    image: dpage/pgadmin4

    container_name: properties_pgadmin_container

    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=unhackable

    ports:
      - 8002:80

    depends_on:
      - scraper


  dashboard:

    build:
      context: ./dashboard

    container_name: properties_dashboard

    ports:
      - 8003:8050

    environment:
      - POSTGRES_PASSWORD=unhackable
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db

    depends_on:
      - scraper
    
  
  jenkins:

    image: jenkins/jenkins:2.414.3-alpine-jdk21-preview

    ports:
      - 8004:8080
      - 50000:50000
    
    restart: on-failure

