version: '3.8'

services:

  postgres:

    image: postgres:14-alpine3.17
    
    volumes:
      - ./db:/var/lib/postgresql/data

    container_name: properties_postgres_db

    ports:
      - 8000:5432

    environment:
      - POSTGRES_PASSWORD=unhackable
      - POSTGRES_USER=postgres

  scraper:
    build: .
    volumes:
      - .:/home/scraper

    container_name: properties_scraper

    ports:
      - 8001:8000

    environment:
      - POSTGRES_HOST=postgres  # FOR DOCKER COMPOSE NETWORKING
      - MYSQL_HOST=mysql  # FOR DOCKER COMPOSE NETWORKING
    
    depends_on:
      - postgres
  
  pdadmin:

    image: dpage/pgadmin4

    container_name: pgadmin_container

    ports:
      - 8002:5432
      - 8003:80

    depends_on:
      - postgres

